#! /bin/bash

gio mime x-scheme-handler/http chromium.desktop
gio mime x-scheme-handler/https chromium.desktop
gio mime application/x-terminal-emulator foot.desktop
gio mime inode/directory caja-browser.desktop

dbus-launch code ${VSCODE_ARGS}
